### ISSUE TITLE
Error with go get github.com/prasmussen/gdrive

### ISSUE THREAD

**Issue by StephanieG60** [prasmussen/gdrive#638]
We are building Raspi Pi devices for Speed Tests and this code has worked before and now has stopped, Below is the error

go get github.com/prasmussen/gdrive
# golang.org/x/oauth2/google/internal/externalaccount
go/src/golang.org/x/oauth2/google/internal/externalaccount/executablecredsource.go:256:15: undefined: io.ReadAll

We have tried multiple OS and WiFi networks.

Any tips would be helpful

**Comment by avenbreaks** [comment]
you can try : 
1. wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
2. tar -xvf gdrive_2.1.1_linux_386.tar.gz
3. ./gdrive about
4. enter your verification code

**Comment by StephanieG60** [comment]
Im getting this when I follow
./gdrive about

And I get this error,
./gdrive about
bash: ./gdrive: cannot execute binary file: Exec format error

Have I made a mistake? I am following the code on this webpage - Compiling and Running gDrive - Pi My Life Up<https://pimylifeup.com/compiling-and-running-gdrive/>

Kind Regards,

Stephanie Green

IT Specialist

[Y4U2]

Mobile: 0437759066
Work : 02 6171 9806
Email: ***@***.******@***.***>

**Comment by cg2v** [comment]
Rasberry Pi is ARM, not i386. You can possibly try https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_arm64.tar.gz instead.

If you can upgrade your go to 1.16 (not 1.17 or newer), then go get may work.
It does work for me on linux using `go version go1.16.2 linux/amd64`, but not `go version go1.13.8 linux/amd64`

**Comment by Mr-Tech-13** [comment]
> you can try :
> 
> 1. wget https://github.com/prasmussen/gdrive/releases/download/2.1.1/gdrive_2.1.1_linux_386.tar.gz
> 2. tar -xvf gdrive_2.1.1_linux_386.tar.gz
> 3. ./gdrive about
> 4. enter your verification code

Thank you so much, this worked on ubuntu 20.04 in a google VM (For anyone trying to reproduce)

**Comment by StephanieG60** [comment]
Hi I managed to get a work around to resolve the gdrive issue but im getting another error that I thought id see if you’ve seen it before.

I think in trying to get these devices to work ive messed up somewhere

Its when I also do go get github.com/prasmussen/gdrive but get this new error

***@***.***:~/gdrive $ go get github.com/prasmussen/gdrive
# runtime/cgo
gcc: error: unrecognized command-line option '-marm'

Would you know anything about this?

**Comment by hgmaleldiin** [comment]
> 
when I tried !./grive about .. I couldn't find any box to enter the verification code in ..why this may happen please?
![image](https://user-images.githubusercontent.com/102483423/183429048-172c9540-e972-4acf-8407-4e01dfb0500d.png)

@avenbreaks

**Comment by cg2v** [comment]
@StephanieG60 That looks like a cross compiler issue. https://github.com/golang/go/issues/16801. You need to set the CC variable to the gcc (or clang) cross compiler for your pi build environment.
